### DISCUSSION TITLE
Change Section styles with `fountain` cssclass yaml

### DISCUSSION THREAD

**Discussion by aram2513** [chuangcaleb/obsidian-fountain-editor#45] [Q & A]
Can I change the font and styling of Markdown formatted Headers (h1, h2, h3, etc) when I apply the fountain CSS Class? I don't want it to affect my entire vault, only script files.

**Comment by chuangcaleb** [comment]
Sorry for late reply, didn't see this—but yeah, you can totally do this, even without a plugin in native Obsidian! You can write a custom CSS Snippet like this:

```css
.markdown-preview-view.my-custom-class h1 {
  color: red;
}
```

when your note's frontmatter looks something like `cssclassses: my-custom-class`
